# Generated by Django 3.2.5 on 2021-07-30 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phome',
            new_name='phone',
        ),
    ]
